sáb 18 jan 2025 01:47:59 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,3 +1,29 @@
+#  Altered: 2024/12/26 - 12:26
+#  Updated: 2025/01/04 - 15:47
+#
+#  Copyright (c) 2024-2025, Vilmar Catafesta <vcatafesta@gmail.com>
+#  All rights reserved.
+#
+#  Redistribution and use in source and binary forms, with or without
+#  modification, are permitted provided that the following conditions
+#  are met:
+#  1. Redistributions of source code must retain the above copyright
+#     notice, this list of conditions and the following disclaimer.
+#  2. Redistributions in binary form must reproduce the above copyright
+#     notice, this list of conditions and the following disclaimer in the
+#     documentation and/or other materials provided with the distribution.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
+#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
+#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
+#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
+#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
+#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
+#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
+#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+##############################################################################
 name: "Build rootfs VoidLinux"
 description: "Builds a tarball rootfs image for VoidLinux"
 
@@ -27,20 +53,140 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - name: Definir a função send_telegram_message no script temporário
+      shell: bash
+      env:
+        TELEGRAM_TOKEN: "${{ inputs.telegram_token }}"
+        TELEGRAM_CHAT_ID: "${{ inputs.telegram_chat_id }}"
+      run: |
+        #Definir a função send_telegram_message no script temporário
+        cat << 'EOF' > /tmp/send_telegram_message.sh
+        export TERM=${TERM:-xterm}
+        export TERM=${TERM:-xterm-256color}
+
+        #Definindo variáveis de cores
+        export red="\033[01;31m"
+        export green="\033[01;32m"
+        export yellow="\033[01;33m"
+        export blue="\033[01;34m"
+        export pink="\033[01;35m"
+        export cyan="\033[01;36m"
+        export reset="\033[0m"
+        alias ls='ls -lha --color=auto'
+        alias dir='ls -lha --color=auto'
+
+        die() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${cyan}error: ${red}${msg}${reset}"
+          exit  1
+        }
+        export -f die
+
+        msg_raw() {
+          local msg="$1"
+          # Remove tags HTML, se existirem
+          #msg="$(sed 's/<[^>]*>//g' <<< "$msg")"
+
+          # Verifica se existe ':' na mensagem
+          if [[ "$msg" == *:* ]]; then
+            # Divide a string antes e depois do primeiro ':'
+            local before_colon="${msg%%:*}:"
+            local after_colon="${msg#*: }"
+            # Aplica as cores
+            msg="${cyan}${before_colon} ${yellow}${after_colon}${reset}"
+          else
+            # Se não houver ':', aplica apenas a cor padrão
+            msg="${cyan}${msg}${reset}"
+          fi
+          echo -e "$msg"
+        }
+        export -f msg_raw
+
+        msg() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${cyan}running: ${yellow}${msg}${reset}"
+        }
+        export -f msg
+
+        msg_ok() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${cyan}feito  : ${green}${msg}${reset}"
+        }
+        export -f msg_ok
+
+        msg_run() {
+          local msg="$1"
+          echo -e "BP=>${cyan}running: ${yellow}${msg}${reset}"
+
+          # Executa o comando e captura o código de saída
+          if ! eval "$msg"; then
+            echo -e "BP=>${red}Erro ao executar: ${yellow}${msg}${reset}" >&2
+            return 1
+          fi
+          return 0
+        }
+        export -f msg_run
+
+        msg_info() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${cyan}info   : ${yellow}${msg}${reset}"
+        }
+        export -f msg_info
+
+        msg_warning() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${red}warning: ${orange}${msg}${reset}"
+        }
+        export -f msg_warning
+
+        replicate() {
+          local char=${1:-'#'}
+          local nsize=${2:-$(tput cols)}
+          local line
+          #printf -v line "%*s" "$nsize" && echo "${line// /$char}"
+          #printf -v line "%*s" "$nsize" && echo -e "\033[31m${line// /$char}\033[0m"
+          printf -v line "%*s" "$nsize" && echo -e "${blue}${line// /$char}${reset}"
+        }
+        export -f replicate
+
+        send_telegram_message() {
+          local message="$1"
+          local parse_mode="$2"
+
+          # Define parse_mode como "MarkdownV2" se não for especificado
+          [[ -z $parse_mode ]] && parse_mode="HTML"
+
+          # Remove as tags HTML e exibe o resultado no terminal
+          echo -e "${green}$(sed 's/<[^>]*>//g' <<< "$message")${reset}"
+          # Envia a mensagem original com HTML para o Telegram
+          curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
+            -d chat_id="${{ inputs.telegram_chat_id }}" \
+            -d text="$message" \
+            -d parse_mode="$parse_mode"
+        }
+        export -f send_telegram_message
+        EOF
+
     - name: Display the current user in CONTAINER
       shell: bash
       run: |
         # Display the current user in CONTAINER
-        echo "##########################################################################"
-        echo "Current host is     : $(hostname)"
-        echo "Current user is     : $(whoami)"
-        echo "Current user ID is  : $(id -u)"
-        echo "Current user details: $(id)"
-        echo "##########################################################################"
+        source /tmp/send_telegram_message.sh
+        replicate "#"
+        msg_raw "Current host is     : $(hostname)"
+        msg_raw "Current user is     : $(whoami)"
+        msg_raw "Current user ID is  : $(id -u)"
+        msg_raw "Current user details: $(id)"
+        replicate "#"
         df -hT || true
-        echo "##########################################################################"
+        replicate "#"
         ls -la /mnt || true
-        echo "##########################################################################"
+        replicate "#"
 
     - name: Setup build environment
       shell: bash
@@ -132,6 +278,8 @@ runs:
         # BUILD ISO Image
         # Denine path for directory
 
+        source /tmp/send_telegram_message.sh
+
         # Check if iso-profiles directory exists before proceeding
         if [[ ! -d "$PROFILE_PATH" ]]; then
           echo "ERRO(L427): Diretório $PROFILE_PATH não localizado!"
@@ -139,26 +287,25 @@ runs:
         fi
 
         # listando diretório iso-profiles no diretório atual
-        ls -la "$WORK_PATH"
+        msg_run "ls -lah $WORK_PATH"
 
         build_mkroot_fs() {
-          echo "########################## RESUMO #################################"
-          echo "BUILD COMMAND            : ./mkrootfs"
-          echo "PROFILE_PATH             : $PROFILE_PATH"
-          echo "EDITION                  : $EDITION"
-          echo "###################################################################"
-          echo "WORK_PATH                : $WORK_PATH"
-          echo "PROFILE_PATH             : $PROFILE_PATH"
-          echo "ISO profiles path        : $PROFILE_PATH/$EDITION"
-          echo "PATH_MANJARO_ISO_PROFILES: $PATH_MANJARO_ISO_PROFILES"
-          echo "###################################################################"
-          #echo "ROOT_RUN_DIR             : $(< /root/.config/manjaro-tools/iso-profiles.conf)"
-          #echo "BUILDUSER_RUN_DIR        : $(< /home/builduser/.config/manjaro-tools/iso-profiles.conf)"
-          echo "###################################################################"
+          replicate "######################### RESUMO #################################"
+          msg_raw "BUILD COMMAND            : ./mkrootfs"
+          msg_raw "PROFILE_PATH             : $PROFILE_PATH"
+          replicate "#"
+          msg_raw "WORK_PATH                : $WORK_PATH"
+          msg_raw "PROFILE_PATH             : $PROFILE_PATH"
+          msg_raw "ISO profiles path        : $PROFILE_PATH/$EDITION"
+          msg_raw "PATH_MANJARO_ISO_PROFILES: $PATH_MANJARO_ISO_PROFILES"
+          #replicate "#"
+          #msg_raw "ROOT_RUN_DIR             : $(< /root/.config/manjaro-tools/iso-profiles.conf)"
+          #msg_raw "BUILDUSER_RUN_DIR        : $(< /home/builduser/.config/manjaro-tools/iso-profiles.conf)"
+          replicate "#"
 
-          pushd "$PROFILE_PATH"
+          pushd "$PROFILE_PATH" > /dev/null || true
           [[ ${{ inputs.tmate }} == 'true' ]] && ./mkrootfs || ./mkrootfs > /dev/null
-          popd
+          popd > /dev/null
         }
 
         cleanup_and_move_files() {
@@ -174,12 +321,10 @@ runs:
 
           if [[ -n "$OUTPUT_ISO_PATH_NAME" ]]; then
             mv -fv "$OUTPUT_ISO_PATH_NAME" "$WORK_PATH/" || echo "ERRO: Falha ao mover arquivo ISO $OUTPUT_ISO_PATH_NAME"
-            # Set environment variables
             echo "ISO_FULLNAME=$WORK_PATH/$ISO_BASENAME" >> "$GITHUB_ENV"
           fi
           if [[ -n "$OUTPUT_XZ_PATH_NAME"  ]]; then
             mv -fv "$OUTPUT_XZ_PATH_NAME" "$WORK_PATH/"  || echo "ERRO: Falha ao mover arquivo XZ $OUTPUT_XZ_PATH_NAME"
-            # Set environment variables
             echo "XZ_FULLNAME=$WORK_PATH/$XZ_BASENAME" >> "$GITHUB_ENV"
           fi
         }
